### ISSUE TITLE
Passwort ändern nicht verfügbar

### ISSUE THREAD

**Issue by mamo1903** [ASV-Aachen/Website#288]
Beim aufrufen der Funktion "passwort ändern" kommt es unmittelbar zu der Fehlermeldung "Es ist ein Fehler aufgetretet - kein Zugriff"

**Comment by Darker97** [comment]
Settings Fehler, sollte behoben sein.

Alle die so eine Meldung ebenfalls haben wenden sich bitte an einen Admin!

---
FÜR ADMINS: Checken ob Nutzer die Role "default-role-ASV" hat. Fehlt diese kann der Nutzer sein eigenes Menü nicht aufrufen.
