### ISSUE TITLE
Fataler Fehler Wiki

### ISSUE THREAD

**Issue by mamo1903** [ASV-Aachen/Website#308]
Am Abend 14.03. bekommt man beim Einloggen ins Wiki folgende Fehlermeldung 
![479E8DD1-592C-46E6-8512-3C23B9945E43](https://user-images.githubusercontent.com/46570896/158276374-629faee8-797a-4f70-8dff-9a0e9a8a04d4.jpeg)

**Comment by Darker97** [comment]
Sollte gelöst sein

---
_Notiz für Dev_
Speicher war voll
